/**************************************************************************
* WARNING: 'git_version.h' is automatically generated by make_patchnum.pl
*          DO NOT EDIT DIRECTLY - edit make_patchnum.pl instead
***************************************************************************/
#define PERL_PATCHNUM "v5.28.0"
#define PERL_GIT_UNPUSHED_COMMITS		\
    /*leave-this-comment*/
#define PERL_GIT_UNCOMMITTED_CHANGES
